dataSchema <- 
  cols_only(
    # `ID`                    = col_character(),
    # `Source`                = col_factor(),
    # `TMC`                   = col_double(),
    `Severity`              = col_factor(levels = c(0,1,2,3,4), ordered = TRUE),
    `Start_Time`            = col_datetime(format = "%Y-%m-%d %H:%M:%S"),
    `End_Time`              = col_datetime(format = "%Y-%m-%d %H:%M:%S"),
    # `Start_Lat`             = col_character(),
    # `Start_Lng`             = col_character(),
    # `End_Lat`               = col_character(),
    # `End_Lng`               = col_character(),
    `Distance(mi)`          = col_double(),
    # `Description`           = col_character(),
    # `Number`                = col_double(),
    # `Street`                = col_character(),
    `Side`                  = col_factor(),
    # `City`                  = col_character(),
    # `County`                = col_character(),
    `State`                 = col_factor(),
    `Zipcode`               = col_character(),
    # `Country`               = col_character(),
    # `Timezone`              = col_character(),
    # `Airport_Code`          = col_character(),
    # `Weather_Timestamp`     = col_datetime(format = "%Y-%m-%d %H:%M:%S"),
    `Temperature(F)`        = col_double(),
    `Wind_Chill(F)`         = col_double(),
    `Humidity(%)`           = col_double(),
    `Pressure(in)`          = col_double(),
    `Visibility(mi)`        = col_double(),
    `Wind_Direction`        = col_factor(),
    `Wind_Speed(mph)`       = col_double(),
    `Precipitation(in)`     = col_double(),
    `Weather_Condition`     = col_factor(),
    `Amenity`               = col_logical(),
    `Bump`                  = col_logical(),
    `Crossing`              = col_logical(),
    `Give_Way`              = col_logical(),
    `Junction`              = col_logical(),
    `No_Exit`               = col_logical(),
    `Railway`               = col_logical(),
    `Roundabout`            = col_logical(),
    `Station`               = col_logical(),
    `Stop`                  = col_logical(),
    `Traffic_Calming`       = col_logical(),
    `Traffic_Signal`        = col_logical(),
    `Turning_Loop`          = col_logical(),
    `Sunrise_Sunset`        = col_factor()
    # `Civil_Twilight`        = col_factor(),
    # `Nautical_Twilight`     = col_factor(),
    # `Astronomical_Twilight` = col_factor()
  )
